# Things:

In [24]:
''' ndarray (a providing vectorized 
    arithmetic operations and sophisticated broadcasting capabilities)
    
''' 

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Let's declare an ndarray: <br><br>
(time and space-efficient multidimensional array)
</p>

In [2]:
import numpy as np

an_array = np.array([3, 33, 333])  # Create a rank 1 array

print(type(an_array))              # Prints "<class 'numpy.ndarray'>"

print(an_array.shape)

print(an_array[0], an_array[1], an_array[2])

an_array[0] = 888                 # Change an element of the array

print(an_array)

<class 'numpy.ndarray'>
(3,)
3 33 333
[888  33 333]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

How to create a Rank 2 numpy array:</p>

In [47]:
another = np.array([[11,12,13],[21,22,23]])   # Create a rank 2 array

print(another.shape)  # rows x columns                   

print(another[0, 0], another[0, 1], another[1, 0])

(2, 3)
11 12 21


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

There are many way to create numpy arrays:
</p>

In [91]:
import numpy as np

ex1 = np.zeros((2,2))      #   an array of zeros
print(ex1)             

print() 
ex2 = np.full((2,2), 9.0)  #   an array filled with 9.0
print(ex2)              

print()
ex3 = np.eye(2)            #   a 2x2  matrix
print(ex3)  

print() 
ex4 = np.ones((1,2))       #   an array of ones
print(ex4)              

print()
ex5 = np.random.random((2,2)) # an array of random values
print(ex5)                     

[[ 0.  0.]
 [ 0.  0.]]

[[ 9.  9.]
 [ 9.  9.]]

[[ 1.  0.]
 [ 0.  1.]]

[[ 1.  1.]]

[[ 0.85755874  0.59682324]
 [ 0.12201789  0.08788861]]


<p style="font-family: Arial; font-size:2.75em;color:#2462C0; font-style:bold"><br>

Array Indexing
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Slice indexing:
</p>

In [89]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)
print()

# Array slicing: get a subarray consisting of the first 2 rows x 2 columns

a_slice = an_array[:2, 1:3]
print(a_slice)
print()

# When you modify a slice, you modify the underlying array

print(an_array[0, 1])    
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print(an_array[0, 1])    

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

[[12 13]
 [22 23]]

12
1000


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Use both integer indexing & slice indexing
</p>

In [88]:
import numpy as np

# Rank 2 array of shape (3, 4)

an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)
print()

# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[1, :]    # Rank 1 view 

# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :]  # Rank 2 view 

print(row_rank1, row_rank1.shape)   
print()
print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

[21 22 23 24] (4,)

[[21 22 23 24]] (1, 4)


In [87]:
# For columns of an array:

print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Array Indexing for changing elements:
</p>

In [17]:
# Create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(an_array)

# Create an array of indices
indices = np.array([0, 1, 2, 0])

whichRows = np.arange(4)
print('\nRows indices picked : %s' % whichRows)

# Select one element from each row
print(an_array[whichRows, indices])

# Change one element from each row
an_array[np.arange(4), indices] += 100000

print('\nChanged Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]

Rows indices picked : [0 1 2 3]
[11 22 33 41]

Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


In [22]:
an_array = np.array([[11,12], [21, 22], [31, 32]])

In [23]:
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [24]:
print(an_array[filter])

[21 22 31 32]


In [25]:
#Can be done this way also:

an_array[an_array > 15]

array([21, 22, 31, 32])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Datatypes:
</p>

In [27]:
ex1 = np.array([11, 12]) # Python assigns the  data type
print(ex1.dtype)

ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

ex3 = np.array([11, 21], dtype=np.int64) #You can also tell Python the  data type
print(ex3.dtype)

int64
float64
int64


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Array Operations:

</p>

In [39]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

[[ 322.1  324.1]
 [ 342.1  344.1]]
[[ 322.1  324.1]
 [ 342.1  344.1]]


In [40]:
print(x - y)
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]
[[-100.1 -100.1]
 [-100.1 -100.1]]


In [41]:
print(x * y)
print(np.multiply(x, y))

[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]
[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]


In [42]:
print(x / y)
print(np.divide(x, y))

[[ 0.52581715  0.52805281]
 [ 0.54726368  0.54930212]]
[[ 0.52581715  0.52805281]
 [ 0.54726368  0.54930212]]


In [43]:
print(np.sqrt(x))

[[ 10.53565375  10.58300524]
 [ 11.          11.04536102]]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Elementwise Operations:

</p>

In [70]:
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [69]:
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

180

180


In [67]:
print(x2d.dot(a1d))
print()
print(np.dot(x2d, a1d))

[18 18]

[18 18]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Sum / Transpose:

</p>

In [73]:
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))          # add all members
print()

print(np.sum(ex1, axis=0))  # columnwise sum
print()

print(np.sum(ex1, axis=1))  # rowwise sum
print()

66

[32 34]

[23 43]



In [74]:
ex1.T

array([[11, 21],
       [12, 22]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Broadcasting:

</p>

In [81]:
start   = np.array([[11,12,13], [21*10,22*10,23*10], [31*100,32*100,33*100], 
                    [41*1000,42*1000,43*1000]])
print(start)
print()

addThis = np.array([1, 0, 1])
print(addThis)
print()

y = start + addThis  # add to each row of 'start' using broadcasting
print(y)

[[   11    12    13]
 [  210   220   230]
 [ 3100  3200  3300]
 [41000 42000 43000]]

[1 0 1]

[[   12    12    14]
 [  211   220   231]
 [ 3101  3200  3301]
 [41001 42000 43001]]


In [27]:
''' Loop less operations

'''

' Loop less operations\n'

In [28]:
''' Read / Write array data to disk

'''

' Read / Write array data to disk\n'

In [29]:
''' Linear algebra, random number generation, and Fourier transform capabilities
'''

' Linear algebra, random number generation, and Fourier transform capabilities\n'

In [6]:
# Down sampling (yearly)
# Particular time of year(monthly)

In [7]:
# Glaciers decreasing
# Sea Level increasing

# Functionality:

In [36]:
''' Fast vectorized array operations for data munging and cleaning, 
    subsetting and filtering, 
    transformation, and any other kinds of computations
'''

' Fast vectorized array operations for data munging and cleaning, \n    subsetting and filtering, \n    transformation, and any other kinds of computations\n'

In [31]:
''' Common array algorithms like sorting, unique, and set operations
'''

' Common array algorithms like sorting, unique, and set operations\n'

In [32]:
''' Efficient descriptive statistics and aggregating/summarizing data
'''

' Efficient descriptive statistics and aggregating/summarizing data\n'

In [33]:
''' Data alignment and relational data manipulations for merging and 
    joining together heterogeneous data sets
'''

' Data alignment and relational data manipulations for merging and \n    joining together heterogeneous data sets\n'

In [34]:
''' Expressing conditional logic as array expressions instead of loops 
    with if-elif-else branches
'''

' Expressing conditional logic as array expressions instead of loops \n    with if-elif-else branches\n'

In [35]:
''' Group-wise data manipulations (aggregation, transformation, 
    function application)
'''

' Group-wise data manipulations (aggregation, transformation, \n    function application)\n'