# Things:

In [24]:
''' ndarray (a providing vectorized 
    arithmetic operations and sophisticated broadcasting capabilities)
    
''' 

# ndarray (time and space-efficient multidimensional array)

In [46]:
import numpy as np

an_array = np.array([3, 33, 333])  # Create a rank 1 array

print(type(an_array))              # Prints "<class 'numpy.ndarray'>"

print(an_array.shape)

print(an_array[0], an_array[1], an_array[2])

an_array[0] = 888                 # Change an element of the array

print(an_array)

<class 'numpy.ndarray'>
(3,)
3 33 333
[888  33 333]


# Rank 2 numpy array

In [47]:
another = np.array([[11,12,13],[21,22,23]])   # Create a rank 2 array

print(another.shape)  # rows x columns                   

print(another[0, 0], another[0, 1], another[1, 0])

(2, 3)
11 12 21


# There are many ways to create numpy arrays

In [57]:
import numpy as np

ex1 = np.zeros((2,2))      #   an array of zeros
print(ex1)             

print() 
ex2 = np.ones((1,2))       #   an array of ones
print(ex2)            

print() 
ex3 = np.full((2,2), 9.0)  #   an array filled with 9.0
print(ex3)              

print()
ex4 = np.eye(2)            #   a 2x2  matrix
print(ex4)             

print()
ex5 = np.random.random((2,2)) # an array of random values
print(ex5)                     

[[ 0.  0.]
 [ 0.  0.]]

[[ 1.  1.]]

[[ 9.  9.]
 [ 9.  9.]]

[[ 1.  0.]
 [ 0.  1.]]

[[ 0.31986519  0.13548431]
 [ 0.78455411  0.29044085]]


In [27]:
''' Loop less operations

'''

' Loop less operations\n'

# Array Indexing

## Slice Indexing

In [64]:
import numpy as np

# Rank 2 array with shape (3, 4)
#  [[11,12,13,14]
#   [21,22,23,24]
#   [31,32,33,34]]
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])

# Array slicing: get a subarray consisting of the first 2 rows
# and columns 1 and 2

a_slice = an_array[:2, 1:3]

# A slice of an array is a view into the original array
# When you change the slice, it will modify the original array

print(an_array[0, 1])    
a_slice[0, 0] = 1000    # b[0, 0] is the same piece of data as a[0, 1]
print(an_array[0, 1])    

12
1000


## Use both integer indexing & slice indexing

In [74]:
import numpy as np

# Rank 2 array with shape (3, 4)
#  [[11,12,13,14]
#   [21,22,23,24]
#   [31,32,33,34]]

an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])

# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[1, :]    # Rank 1 view 

# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :]  # Rank 2 view 

print(row_rank1, row_rank1.shape)   
print()
print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

[21 22 23 24] (4,)

[[21 22 23 24]] (1, 4)


In [76]:
# Similarly, for columns of an array:

print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [28]:
''' Read / Write array data to disk

'''

' Read / Write array data to disk\n'

In [29]:
''' Linear algebra, random number generation, and Fourier transform capabilities
'''

' Linear algebra, random number generation, and Fourier transform capabilities\n'

In [6]:
# Down sampling (yearly)
# Particular time of year(monthly)

In [7]:
# Glaciers decreasing
# Sea Level increasing

# Functionality:

In [36]:
''' Fast vectorized array operations for data munging and cleaning, 
    subsetting and filtering, 
    transformation, and any other kinds of computations
'''

' Fast vectorized array operations for data munging and cleaning, \n    subsetting and filtering, \n    transformation, and any other kinds of computations\n'

In [31]:
''' Common array algorithms like sorting, unique, and set operations
'''

' Common array algorithms like sorting, unique, and set operations\n'

In [32]:
''' Efficient descriptive statistics and aggregating/summarizing data
'''

' Efficient descriptive statistics and aggregating/summarizing data\n'

In [33]:
''' Data alignment and relational data manipulations for merging and 
    joining together heterogeneous data sets
'''

' Data alignment and relational data manipulations for merging and \n    joining together heterogeneous data sets\n'

In [34]:
''' Expressing conditional logic as array expressions instead of loops 
    with if-elif-else branches
'''

' Expressing conditional logic as array expressions instead of loops \n    with if-elif-else branches\n'

In [35]:
''' Group-wise data manipulations (aggregation, transformation, 
    function application)
'''

' Group-wise data manipulations (aggregation, transformation, \n    function application)\n'