# numpy Exercise Notebook:

In [2]:
# import appropriate libraries
import numpy as np
import math
# import etc.....
import Tester

# Setup Notebook

Import appropriate libraries.  Can import the Tester, but it's better to import at the point of testing.

In [9]:
mat = np.array(
      [[ 0.35066314,  0.94844269,  0.69324339,  0.32790416],
       [ 0.7935923 ,  0.9212632 ,  0.13607887,  0.56358399],
       [ 0.25597054,  0.74834666,  0.81322464,  0.11280075],
       [ 0.53822742,  0.63970183,  0.1439784 ,  0.58045905]])
mat

array([[ 0.35066314,  0.94844269,  0.69324339,  0.32790416],
       [ 0.7935923 ,  0.9212632 ,  0.13607887,  0.56358399],
       [ 0.25597054,  0.74834666,  0.81322464,  0.11280075],
       [ 0.53822742,  0.63970183,  0.1439784 ,  0.58045905]])

In [10]:
# create a slice array[:2,1:3]
mat[:2, 1:3]

array([[ 0.94844269,  0.69324339],
       [ 0.9212632 ,  0.13607887]])

In [11]:
# update array element
mat[:2, 1:3] += 1000

In [14]:
# boolean indexing
mat[mat<1.5]

array([ 0.35066314,  0.32790416,  0.7935923 ,  0.56358399,  0.25597054,
        0.74834666,  0.81322464,  0.11280075,  0.53822742,  0.63970183,
        0.1439784 ,  0.58045905])

In [23]:
mat = np.array(mat, dtype=np.int)
mat

array([[   0, 1000, 1000,    0],
       [   0, 1000, 1000,    0],
       [   0,    0,    0,    0],
       [   0,    0,    0,    0]])

In [20]:
mat[mat % 2 == 0] = 55

In [24]:
# means by row
mat.mean(axis = 1)

array([ 500.,  500.,    0.,    0.])

In [25]:
np.unique(mat)

array([   0, 1000])

In [27]:
# broadcasting
# take first row and add to each row
first = mat[0,:]
first

array([   0, 1000, 1000,    0])

In [32]:
mat + mat[0,:]

array([[   0, 2000, 2000,    0],
       [   0, 2000, 2000,    0],
       [   0, 1000, 1000,    0],
       [   0, 1000, 1000,    0]])

# Exercise 1

Tell them what is expected of them.  Here, we'll ask them to create a function find max.....

In the cell below, we tell them to modify the cell and possibly give them some starter/helper code.

In [4]:
# modify this cell

def findMax(someList):
    ### BEGIN SOLUTION
    return min(someList)
    ### END SOLUTION
    

In [5]:
# notice this cell is marked as "Autograder tests" and is labelled with an ID (here just ex1, but this is arbitrary for us)
# we can also give points based on the cell completing.  If the code executes without an exception, they are given points.
# so our test cases will throw exceptions if they make errors (and, preferably, give them feedback why.)
import Tester
Tester.ex1(findMax)

Error on blah


AssertionError: Assert failure

Once the notebook is all done, we want to be able to build a notebook the learners can use. This new notebook will just have the read only pieces embedded in the markup.  When you get to that point, here's how to create the notebook for release.

Commands to run to build the notebook for learners:
1.  create a folder in "source" called "assignment_name" (e.g. numpy)
2.  create a symlink to the notebook and required files in the "assignment_name" folder (ln -s filename .)
3.  command1: **nbgrader db assignment add "assignment_name"**
4.  command2: **nbgrader assign "assignment_name"**
5.  Look in the release folder for the student files.